language: node_js
node_js:
  - "8"
cache: npm
install:
  - npm install
script:
  - npm run lint
  - npm run test:unit
  - npm run build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist
    on:
      branch: master
